### ISSUE TITLE
Question about m_add_

### ISSUE THREAD

**Issue by yuyijie1995** [WeitaoVan/L-GM-loss#10]
I am reading your cpp code and have some question about the parameter m_add_,
//////////////////////////////////////////
template <typename Dtype>
static __global__ void margin_top(const int M_, const int N_,
    Dtype *top_data, const Dtype *label, const Dtype margin_mul, const Dtype margin_add) {

    CUDA_KERNEL_LOOP(i, M_) {
        const int y = (int)label[i];
        top_data[i*N_ + y] += top_data[i*N_ + y] * margin_mul - margin_add;
        
    }
}
///////////////////////////////////////
but I do not find the Initialization value of the margin_add in the cifar100 example's trainval.prototext.  Can you tell me something about the parameter margin_add? 
And I found you do not use the margin_add parameter in your tensorflow edition. Is this parameter not matter? 
Look forward to your reply

**Comment by WeitaoVan** [comment]
The parameter 'margin_add' or 'm_add_' is what we have tried during research.
Actually we've found that this parameter does not bring benifits. So we do not use it anymore.
Still, it is in the code. We should have cleared it.
