### ISSUE TITLE
Is eq. 23 implemented correctly?

### ISSUE THREAD

**Issue by eldercrow** [WeitaoVan/L-GM-loss#2]
In eq. 23 in the paper, derivative w.r.t x_i is 
[(1 - p_zi)(1 + alpha) + lambda] Sigma^-1 (x - myu_zi) - ... , 

but the implementation (class_distance_layer.cu, line 227) looks like
[(1 - p_zi)(1 + alpha) Sigma^-1 + lambda] (x - myu_zi). 

I wonder either the writing or the implementation is incorrect, though it is highly likely that it is I who is wrong (I am not very good at math).

**Comment by WeitaoVan** [comment]
Thanks for asking.
Both are correct.

Let's denote the two formulations your wrote as (1) and (2).
For (1), which is exactly what Eq.23 says, it considers the Variance when computing the likelihood.
For (2), it does not consider the Variance when computing the likelihood, which is sometimes easier to converge.

We have tested both ways. Both are okay. You can move the 'divide sigma' from inside the bracket to outside the bracket to try (1). This suits for line 178, 200, 227, 252.

Thanks.

**Comment by eldercrow** [comment]
Thanks a lot for the clarification!
