### ISSUE TITLE
question about feature var

### ISSUE THREAD

**Issue by yuyijie1995** [WeitaoVan/L-GM-loss#9]
In the tensorflow readme ,you said "This is the tensorflow demo for the LGM loss.
While the caffe version is more complete, this version does not support updating of the feature variances." ,but ,in the caffe edition,you also said "Fix the variances to initial values (1.0).". What is the difference?

**Comment by WeitaoVan** [comment]
in the readme.md please read that sentence together with the one above it

> update_sigma: false

> Fix the variances to initial values (1.0).

which means that the parameter `update_sigma` allows us to choose whether to update the variances or not.
